"""Add analytics table

Revision ID: 155e7ce7c3de
Revises: ef6113d723af
Create Date: 2025-07-01 17:03:10.926018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155e7ce7c3de'
down_revision = 'ef6113d723af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('week_end', sa.DateTime(), nullable=False),
    sa.Column('tasks_scheduled', sa.Float(), nullable=True),
    sa.Column('tasks_completed', sa.Float(), nullable=True),
    sa.Column('tasks_in_progress', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Integer(), nullable=True),
    sa.Column('average_task_duration', sa.Integer(), nullable=True),
    sa.Column('most_active_day', sa.String(length=10), nullable=True),
    sa.Column('top_category', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    # ### end Alembic commands ###
